[package]
name = "node"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
provider.workspace = true
transaction_pool.workspace = true
payload.workspace = true
consensus.workspace = true
network.workspace = true
database.workspace = true

